In [58]:
import numpy

# Run by: $python multiplier.py --n=3 --alu==<filename>


from optparse import OptionParser
parser = OptionParser()
parser.add_option("--n", dest="n", default=3)
parser.add_option("-f", dest="filename", default="")
parser.add_option("--alu", dest="myfile", default="ALU.txt")

(opts, args) = parser.parse_args()
n = int(opts.n)

def read(filename):
    lines = open(filename, 'r').read().splitlines()
    A = []
    L = []
    U = []
    matrix = A
    counter = 0;
    for line in lines:
        if counter%n != 0 or counter == 0:
            matrix.append(list(map(float, line.split(" ")[:-1])))
            counter = counter + 1
        else:
            if(counter == n):
                matrix = L
            elif(counter == 2*n):
                matrix = U
            matrix.append(list(map(float, line.split(" ")[:-1])))
            counter = counter + 1
        if(counter == 3*n):
            break
    return A, L, U

def printMatrix(matrix):
    matrix = numpy.array(matrix)
    for line in matrix:
#         print ("\t".join(map(str,line)))
        print(line)

A, L, U = read(opts.myfile)
L = numpy.matrix(L)
U = numpy.matrix(U)
C = L * U # easy and intuitive, isn't it?
printMatrix(C)
# printMatrix(A)
# printMatrix(B)




[7. 8. 9.]
[1. 2. 3.]
[4. 5. 6.]
