In [16]:
import numpy
from skfeature.utility.sparse_learning import calculate_l21_norm

# Run by: $python multiplier.py --n=3 --alu==<filename>


from optparse import OptionParser
parser = OptionParser()
parser.add_option("--n", dest="n", default=4)
parser.add_option("-f", dest="filename", default="")
parser.add_option("--alu", dest="myfile", default="ALU.txt")

(opts, args) = parser.parse_args()
n = int(opts.n)

def read(filename):
    lines = open(filename, 'r').read().splitlines()
    A = []
    Ares = []
    L = []
    U = []
    Pi = []
    matrix = A
    counter = 0;
    for line in lines:
#         print(line)
        if counter%n != 0 or counter == 0:
            matrix.append(list(map(float, line.split(" ")[:-1])))
            counter = counter + 1
        else:
            if(counter == n):
                matrix = Ares
            elif(counter == 2*n):
                matrix = L
            elif(counter == 3*n):
                matrix = U
            elif(counter == 4*n):
                matrix = Pi
            matrix.append(list(map(float, line.split(" ")[:-1])))
            counter = counter + 1
        if(counter == 5*n):
            break
    return A, Ares, L, U, Pi

def printMatrix(matrix):
    matrix = numpy.array(matrix)
    for line in matrix:
#         print ("\t".join(map(str,line)))
        print(line)

A, Ares, L, U, Pi = read(opts.myfile)
A = numpy.matrix(A)
P = numpy.zeros((n,n))
# Pi = numpy.matrix(Pi)
Ares = numpy.matrix(Ares)
L = numpy.matrix(L)
U = numpy.matrix(U)

for x in range(n):
    P[x][int(Pi[0][x])] = 1

C = L * U # easy and intuitive, isn't it?
D = P * A
ans = D - C
printMatrix(ans)

# util.sparse_learning.calculate_l21_norm(ans)
# printMatrix(D)
# printMatrix(A)
# printMatrix(B)




[0. 0. 0. 0.]
[3.55271368e-15 3.99680289e-15 1.72084569e-15 1.33226763e-15]
[-3.55271368e-15 -5.32907052e-15 -2.22044605e-15  0.00000000e+00]
[-2.66453526e-15 -1.77635684e-15 -6.66133815e-16  0.00000000e+00]
